droidcloud/urls.py
#encoding=utf-8
from django.conf.urls import patterns, include, url
from django.contrib import admin
import droidcloud.books.views
import droidcloud.contact.views

admin.autodiscover()

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()


urlpatterns = patterns('',
    # Examples:
     #url(r'^$', 'droidcloud.views.home', name='home'),
     #url(r'^droidcloud/', include('droidcloud.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'^search/$', 'droidcloud.books.views.search'),
    url(r'^contact/$', 'droidcloud.contact.views.contact'),
    url(r'^publishers/$', droidcloud.books.views.PublisherList.as_view())
)

droidcloud/books/models.py
#encoding=utf-8
from django.db import models

class Publisher(models.Model):
    name = models.CharField(max_length=30)
    address = models.CharField(max_length=50)
    city = models.CharField(max_length=60)
    state_province = models.CharField(max_length=30)
    country = models.CharField(max_length=50)
    website = models.URLField(blank = True)
    def __unicode__(self):
        return self.name
    
    class Meta:
        ordering = ['name']

class Author(models.Model):
    first_name = models.CharField(verbose_name = u'名',max_length=30)
    last_name = models.CharField(verbose_name = u'姓', max_length=40)
    email = models.EmailField()
    def __unicode__(self):
        return u'%s %s' % (self.last_name, self.first_name)

class BookManager(models.Manager):
    def title_count(self, keyword):
        return self.filter(title__icontains=keyword).count()

class Book(models.Model):
    title = models.CharField(max_length=100)
    authors = models.ManyToManyField(Author)
    publisher = models.ForeignKey(Publisher)
    publication_date = models.DateField()
    #forumsite = models.URLField(blank = True)
    def __unicode__(self):
        return self.title

droidcloud/contact/forms.py
from django import forms

class ContactForm(forms.Form):
    subject = forms.CharField()
    email = forms.EmailField(required=False, label = 'Your Email')
    message = forms.CharField(widget=forms.Textarea, label='Input Message')
    
    def clean_message(self):
        message = self.cleaned_data['message']
        num_words = len(message.split())
        if num_words < 4:
            raise forms.ValidationError("Not enough words!")
        return message
    

droidcloud/books/views.py
from django.http import HttpResponse
from django.shortcuts import render_to_response
from models import Book
from django.views.generic import ListView
from models import Publisher

class PublisherList(ListView):
    model = Publisher
    template_name = 'publisher_list_page.html'

def search(request):
    errors = []
    if 'q' in request.GET:
        q = request.GET['q']
        if not q:
            errors.append('Enter a search term.')
        elif len(request.GET['q']) > 20:
            errors.append('Please enter a search term less than 20 chars.')
        else:
            books = Book.objects.filter(title__icontains=q)
            return render_to_response('search_results.html', {'books': books, 'query': q})

    return render_to_response('search_form.html', {'errors': errors})

droidcloud/contact/views.py
from django.core.mail import send_mail
from django.http import HttpResponseRedirect
from django.shortcuts import render_to_response
from django.template.context import RequestContext
from droidcloud.contact.forms import ContactForm

def contact(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid(): 
            c_d = form.cleaned_data
            send_mail(
                c_d['subject'],
                c_d['message'],
                c_d.get('email', 'noreply@example.com'),
                ['siteowner@example.com'],
            )
            return HttpResponseRedirect('/contact/thanks/')
    else:
        form = ContactForm(initial={'subject': 'I love your site!'})

    return render_to_response('contact_form.html', {'form': form}, context_instance=RequestContext(request))

droidcloud/templates/base.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN">
<html lang="en">
<head>
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <h1>My helpful timestamp site {{ author }} </h1>
    {% block content %}{% endblock %}
    {% block footer %}
    <hr>
    <p>Thanks for visiting my site.</p>
    {% endblock %}
</body>
</html>

droidcloud/templates/contact_form.html
<html>
<head>
    <title>Contact us</title>
</head>
<body>
    <h1>Contact us</h1>

    {% if form.errors %}
        <p style="color: red;">
            Please correct the error{{ form.errors|pluralize }} below.
        </p>
    {% endif %}

    <form action="" method="post">
    {% csrf_token %} 
        <div class="field">
            {{ form.subject.errors }}
            <label for="id_subject">Subject:</label>
            {{ form.subject }}
        </div>
        <div class="field">
            {{ form.email.errors }}
            <label for="id_email">Your e-mail address:</label>
            {{ form.email }}
        </div>
        <div class="field">
            {{ form.message.errors }}
            <label for="id_message">Message:</label>
            {{ form.message }}
        </div>
        <input type="submit" value="Submit">
    </form>
</body>
</html>

droidcloud/templates/current_datetime.html
{% extends "base.html" %}

{% block title %}The current time{% endblock %}

{% block content %}
<p>It is now {{ current_date }}.</p>
{% endblock %}

droidcloud/templates/offset_datetime.html
{% extends "base.html" %}

{% block title %}Future time{% endblock %}

{% block content %}
<p>In {{ hour_offset }} hour(s), it will be {{ next_time }}.</p>
{% endblock %}

droidcloud/templates/publisher_list_page.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN">
<html lang="en">
<head>
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <h2>Publishers</h2>
    <ul>
        {% for publisher in object_list %}
            <li>{{ publisher.name }}</li>
        {% endfor %}
    </ul>
</body>
</html>

droidcloud/templates/search_form.html
<html>
<head>
    <title>Search</title>
</head>
<body>
   {% if errors %}
       <ul>
          {% for error in errors %}
              <li style="color: red;">{{ error }}</li>
          {% endfor %}
       </ul>
   {% endif %}
    <form action="" method="GET">
        <input type="text" name="q">
        <input type="submit" value="Search">
    </form>
</body>
</html>

droidcloud/templates/search_results.html
<p>You searched for: <strong>{{ query }}</strong></p>

{% if books %}
    <p>Found {{ books|length }} book{{ books|pluralize }}.</p>
    <ul>
        {% for book in books %}
        <li>{{ book.title }}</li>
        {% endfor %}
    </ul>
{% else %}
    <p>No books matched your search criteria.</p>
{% endif %}